# Generated by Django 5.0.6 on 2026-08-31 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('avatar_emoji', models.CharField(default='🏃', max_length=10)),
                ('primary_color', models.CharField(default='#00f2fe', max_length=20)),
                ('secondary_color', models.CharField(default='#4facfe', max_length=20)),
                ('accent_color', models.CharField(default='#ff007f', max_length=20)),
                ('bonus_multiplier', models.FloatField(default=1.0)),
                ('bonus_coin_chance', models.FloatField(default=0.0)),
                ('unlock_cost_coins', models.PositiveIntegerField(default=0)),
                ('unlock_cost_gems', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'unlock_cost_coins'],
            },
        ),
        migrations.CreateModel(
            name='CharacterSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('body_color', models.CharField(default='#22d3ee', max_length=20)),
                ('cloth_color', models.CharField(default='#0284c7', max_length=20)),
                ('shoes_color', models.CharField(default='#f59e0b', max_length=20)),
                ('glow_color', models.CharField(default='#38bdf8', max_length=20)),
                ('unlock_cost_coins', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='players.character')),
            ],
            options={
                'unique_together': {('character', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('high_score', models.BigIntegerField(default=0)),
                ('total_score', models.BigIntegerField(default=0)),
                ('total_distance_m', models.FloatField(default=0.0)),
                ('total_coins', models.PositiveIntegerField(default=100)),
                ('total_gems', models.PositiveIntegerField(default=5)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('magnet_level', models.PositiveIntegerField(default=1)),
                ('multiplier_level', models.PositiveIntegerField(default=1)),
                ('shield_level', models.PositiveIntegerField(default=1)),
                ('jetpack_level', models.PositiveIntegerField(default=1)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('music_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.character')),
                ('active_skin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.characterskin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.character')),
                ('skin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.characterskin')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='players.playerprofile')),
            ],
            options={
                'verbose_name_plural': 'Player Inventories',
            },
        ),
    ]
