# Generated by Django 5.0.6 on 2026-08-31 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField(default=0)),
                ('distance_m', models.FloatField(default=0.0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('character_used', models.CharField(default='dash', max_length=50)),
                ('timeframe', models.CharField(choices=[('ALL_TIME', 'All-Time'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily')], default='ALL_TIME', max_length=20)),
                ('period_key', models.CharField(default='all', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['timeframe', 'period_key', '-score'], name='leaderboard_timefra_8bd5d7_idx')],
                'unique_together': {('user', 'timeframe', 'period_key')},
            },
        ),
    ]
