# Generated by Django 5.0.6 on 2026-08-31 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mission_type', models.CharField(choices=[('DAILY', 'Daily Challenge'), ('REPEATABLE', 'Career Mission')], default='DAILY', max_length=20)),
                ('objective_type', models.CharField(choices=[('COINS_SINGLE_RUN', 'Collect Coins in One Run'), ('COINS_TOTAL', 'Collect Total Coins'), ('DISTANCE_SINGLE_RUN', 'Reach Distance in One Run'), ('DISTANCE_TOTAL', 'Reach Total Distance'), ('SCORE_SINGLE_RUN', 'Score Points in One Run'), ('POWERUPS_COLLECTED', 'Collect Powerups'), ('TRAINS_DODGED', 'Dodge Moving Trains')], max_length=30)),
                ('target_value', models.BigIntegerField(default=100)),
                ('reward_coins', models.PositiveIntegerField(default=150)),
                ('reward_gems', models.PositiveIntegerField(default=1)),
                ('icon', models.CharField(default='🎯', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.BigIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_missions', to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mission', 'assigned_date')},
            },
        ),
    ]
