# Generated by Django 5.0.6 on 2026-08-31 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.BigIntegerField(default=0)),
                ('distance_m', models.FloatField(default=0.0)),
                ('coins_collected', models.PositiveIntegerField(default=0)),
                ('max_multiplier', models.FloatField(default=1.0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('powerups_used_count', models.PositiveIntegerField(default=0)),
                ('death_cause', models.CharField(choices=[('TRAIN_COLLISION', 'Train Collision'), ('BARRIER_COLLISION', 'Barrier Collision'), ('OBSTACLE_COLLISION', 'Obstacle Collision'), ('FALL_OFF_TRACK', 'Fall Off Track'), ('FORFEIT', 'Forfeit / Exit')], default='OBSTACLE_COLLISION', max_length=30)),
                ('character_used', models.CharField(default='dash', max_length=50)),
                ('skin_used', models.CharField(default='classic-cyan', max_length=50)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='game.gamesession')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_sec', models.FloatField()),
                ('event_type', models.CharField(max_length=50)),
                ('lane', models.IntegerField(default=0)),
                ('speed', models.FloatField(default=0.0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='game.gamerun')),
            ],
        ),
    ]
